language: node_js
node_js:
- '0.10'
before_install: npm install -g istanbul codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 37368877390b56df3dc3ee9f44c325490bfa4124d3f3b4128ef2593869145a86
after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cat coverage/lcov.info | codeclimate'
notifications:
  slack:
    secure: EYsDK6x/ez0y8R1VhrA1qA5sMK5sgeokt4LY41t5jbgEGCt+8KYXDWqj9xcqrhvwIYXG6iUiNavTTT7jBHb2QxOeH6HyMtIEq3GOBxRNZ5beDJXK1HzYRCTruvik3Ogxg5Nwye2rf6BxCOeu9d7z12IjOSTt2rZMtUukYNDpBhk=
deploy:
  provider: npm
  email: "hashan.punchihewa@gmail.com"
  api_key: "x28n90Y4CrvfNcgJhXmtBgTIEFJxHHuUTkyef0nKXxJPL+gcwDpxrnCB3vHWIjcrRYQvfAqXSJ4Kh/2zj/dlE74UdVoiEDYbtBbNw2qU/duRQRMnabLZK9UGhdBskyvk30bMMckJlUdzJGMTKJtDS3HVJFYU51k9gu/gvS7CDeE="
  on:
    tags: true
    all_branches: true